#!/bin/sh
mvn clean package && docker build -t muzammilnagariya/EDSClient .
docker rm -f EDSClient 2>/dev/null || true && docker run -it --name EDSClient -p 8080:8080 -p 4848:4848 -p 8181:8181 --name EDSClient muzammilnagariya/EDSClient
